version: "3"

services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
      - "9003:9003"
    volumes:
      - ./backend:/home/app
    environment:
      - WORKSPACE=/home/app    
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:9003 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]

  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/home/app
    environment:
      - WATCHPACK_POLLING=true