version: "3"

services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    volumes:
      - ./backend:/home/app

  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/home/app
    environment:
      - WATCHPACK_POLLING=true